# -------------------------------------------------------------------------- #
# Copyright 2002-2013, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------

$: << './'

require 'rubygems'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern    = 'spec/job_spec.rb'
  t.rspec_opts = '-f s --colour'
end

task :clean do
    require 'rubygems'
    require 'mongo'
    require 'yaml'

    CONFIGURATION_FILE = File.dirname(__FILE__) + '/etc/appconverter-server.conf'
    APPCONVERTER_DB_NAME = 'appconverter_dev'

    begin
        CONF      = YAML.load_file(CONFIGURATION_FILE)
    rescue Exception => e
        STDERR.puts "Error parsing config file #{CONFIGURATION_FILE}: #{e.message}"
        exit 1
    end

    Mongo::Connection.new(CONF['db_host'], CONF['db_port']).drop_database(APPCONVERTER_DB_NAME)
end

task :test => [
    :clean,
    :spec
]
