#!/usr/bin/env ruby

ONE_LOCATION = ENV["ONE_LOCATION"]

if !ONE_LOCATION
    LOG_LOCATION = "/var/log/one"
    ETC_LOCATION = "/etc/one"
    RUBY_LIB_LOCATION = "/usr/lib/one/ruby"
else
    LOG_LOCATION = ONE_LOCATION + "/var"
    ETC_LOCATION = ONE_LOCATION + "/etc"
    RUBY_LIB_LOCATION = ONE_LOCATION+"/lib/ruby"
end

CONFIGURATION_FILE   = ETC_LOCATION + "/appconverter-worker.conf"

$: << RUBY_LIB_LOCATION + '/appconverter'

###############################################################################
# Libraries
###############################################################################
require 'appconverter-client'

require 'rubygems'
require 'json'

url = ARGV[0]
job_json = ARGV[1]

client = AppConverter::Client.new

result_path = '/tmp/appconverter_result'
file = File.open(result_path, 'r') {|f|
    str = f.read
    client.callback(url, str.strip)
}


