#!/usr/bin/env ruby

#------------------------------------------------------------------------------#
# Copyright 2002-2014, OpenNebula Project (OpenNebula.org), OpenNebula Systems #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License"); you may      #
# not use this file except in compliance with the License. You may obtain      #
# a copy of the License at                                                     #
#                                                                              #
# http://www.apache.org/licenses/LICENSE-2.0                                   #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
#------------------------------------------------------------------------------#

ONE_LOCATION = ENV["ONE_LOCATION"]

if !ONE_LOCATION
    LOG_LOCATION = "/var/log/one"
    ETC_LOCATION = "/etc/one"
    RUBY_LIB_LOCATION = "/usr/lib/one/ruby"
else
    LOG_LOCATION = ONE_LOCATION + "/var"
    ETC_LOCATION = ONE_LOCATION + "/etc"
    RUBY_LIB_LOCATION = ONE_LOCATION+"/lib/ruby"
end

CONFIGURATION_FILE   = ETC_LOCATION + "/appconverter-worker.conf"

$: << RUBY_LIB_LOCATION + '/appconverter'
$: << RUBY_LIB_LOCATION + '/appconverter/lib'
$: << RUBY_LIB_LOCATION + '/oneapps/market'

################################################################################
# Libraries
################################################################################

require 'appmarket_client'
require 'appliance_handler'

require 'rubygems'
require 'json'
require 'base64'
require 'yaml'
require 'open4'
require 'digest/md5'
require 'digest/sha1'

require 'pp'

################################################################################
# Configuration
################################################################################

begin
    AppMarket::CONF = YAML.load_file(CONFIGURATION_FILE)
rescue Exception => e
    STDERR.puts "Error parsing config file #{CONFIGURATION_FILE}: #{e.message}"
    exit 1
end

################################################################################
# Helper Methods
################################################################################

def fail(error_payload)
    @client.callback(@callback_url, "error", error_payload)
end

def ensure_value(value, error_msg)
    fail(error_msg) if value.nil? or value.empty?
end

################################################################################
# Main
################################################################################

# Callback URL
@callback_url = ARGV[0]

username = AppMarket::CONF[:username]
password = AppMarket::CONF[:password]
url      = AppMarket::CONF[:appmarket_url]

@client = AppMarket::Client.new(username, password, url)

# Job meta-data
begin
    job_json = JSON.parse(Base64::decode64(ARGV[1]))
rescue
    STDERR.puts("Invalid job.")
    exit 1
end

source      = job_json["appliance"]["source"]
source_type = job_json["appliance"]["source_type"]

ensure_value(source,      "Attribute 'source' cannot be empty.")
ensure_value(source_type, "Attribute 'source_type' cannot be empty.")

begin
    case source_type
    when "ova" then klass = OVA
    else
        raise WorkerFile, "Unknown source_type: #{type}"
    end

    appliance = klass.new(job_json["appliance"])
    appliance.unpack
    appliance.register_files
    appliance.delete_temp_dir
rescue Exception => e
    error_payload = {"job"=>{"error_message" => "[#{e.class.to_s}] #{e.message}"}}
    STDERR.puts("[#{e.class.to_s}] #{e.message}\n#{e.backtrace}")
    fail(error_payload.to_json)
    exit 0
end

appliance_payload ={"appliance" => appliance.to_hash}
@client.callback(@callback_url, "done", appliance_payload.to_json)
