#------------------------------------------------------------------------------#
# Copyright 2002-2014, OpenNebula Project (OpenNebula.org), OpenNebula Systems #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License"); you may      #
# not use this file except in compliance with the License. You may obtain      #
# a copy of the License at                                                     #
#                                                                              #
# http://www.apache.org/licenses/LICENSE-2.0                                   #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
#------------------------------------------------------------------------------#

source "http://rubygems.org"

if RUBY_VERSION < "1.9"
    gem 'nokogiri', '<1.6.0'
    gem 'mime-types', '<2'
else
    gem 'nokogiri'
end

gem 'json'
gem 'haml'
gem 'sinatra'
gem 'mongo'
gem 'bson_ext'
gem 'redcarpet', '<3.0.0'
gem 'mail'
gem 'bcrypt'
gem 'opennebula-cli'
